import { ChangeDetectionStrategy, Component, Input, OnChanges, SimpleChanges, computed, inject, signal } from "@angular/core";
import { CommonModule } from "@angular/common";
import { ChatStateService } from "../../services/chat-state.service";
import { IconComponent } from "../icon/icon.component";

/**
 * "Catch me up" banner shown inline at the top of an unread conversation.
 * If the AI has prepared a summary for this conv (via AI_UNREAD_SUMMARIES),
 * the user gets a one-tap recap with the actions the AI thinks they should
 * take next — saves them having to scroll back through dozens of messages.
 *
 * Visibility rules:
 *   - The conv must have an entry in AI_UNREAD_SUMMARIES
 *   - The conv must be unread (no summary banner needed if you've already
 *     caught up)
 *   - The user can dismiss the banner — that state is per-tab (signal),
 *     not persisted; refreshing brings it back so the user can re-check.
 */
@Component({
  selector: "app-ai-catchup-banner",
  standalone: true,
  imports: [CommonModule, IconComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div *ngIf="visible()"
         class="mx-3 mt-3 mb-1 rounded-2xl border border-purple-100 bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50 p-3 shadow-sm">
      <div class="flex items-start gap-3">
        <div class="w-7 h-7 shrink-0 rounded-md bg-gradient-to-br from-blue-500 via-purple-500 to-pink-500 flex items-center justify-center">
          <app-icon name="sparkles" [size]="14" [class]="loading() ? 'text-white animate-pulse' : 'text-white'"></app-icon>
        </div>
        <div class="flex-1 min-w-0">
          <div class="flex items-baseline gap-2 flex-wrap">
            <span class="text-[11px] font-bold uppercase tracking-wider text-purple-700">Catch me up</span>
            <span *ngIf="!loading() && summary()?.severity" [class]="severityClass()">{{ summary()?.severity }}</span>
            <span *ngIf="loading()" class="catchup-skeleton h-3 w-14 rounded-full"></span>
          </div>

          <!-- Loading skeleton — shimmering placeholder lines that
               approximate the bullet-recap shape. Renders only while
               the LLM is producing the summary; replaced with the
               real text + action chips when the response lands. -->
          <ng-container *ngIf="loading() && !summary(); else readyContent">
            <div class="mt-2 space-y-2">
              <div class="catchup-skeleton h-3 w-[92%] rounded"></div>
              <div class="catchup-skeleton h-3 w-[78%] rounded"></div>
              <div class="catchup-skeleton h-3 w-[60%] rounded"></div>
            </div>
            <div class="flex items-center gap-1.5 mt-3">
              <span class="catchup-skeleton h-4 w-16 rounded-full"></span>
              <span class="catchup-skeleton h-4 w-20 rounded-full"></span>
              <span class="catchup-skeleton h-4 w-12 rounded-full"></span>
            </div>
          </ng-container>

          <ng-template #readyContent>
            <div class="text-[13px] text-gray-800 mt-1 leading-relaxed">{{ summary()?.summary }}</div>

            <!-- Suggested actions -->
            <div *ngIf="summary()?.actions?.length" class="flex items-center gap-1.5 mt-2 flex-wrap">
              <span *ngFor="let a of summary()?.actions"
                    class="text-[11px] bg-white/80 ring-1 ring-purple-100 text-purple-700 rounded-full px-2 py-0.5">
                {{ a }}
              </span>
            </div>

            <!-- Footer actions -->
            <div class="flex items-center gap-2 mt-2.5">
              <button
                (click)="markRead()"
                class="text-[12px] font-medium text-purple-700 hover:text-purple-900 px-2 py-1 rounded hover:bg-white/70 transition"
              >Mark as read</button>
              <span class="text-gray-300">·</span>
              <button
                (click)="dismiss()"
                class="text-[12px] text-gray-500 hover:text-gray-800 px-2 py-1 rounded hover:bg-white/70 transition"
              >Dismiss</button>
              <span class="text-[10px] text-gray-400 ml-auto">Generated by Airlift Intelligence</span>
            </div>
          </ng-template>
        </div>

        <!-- Quick close X -->
        <button
          (click)="dismiss()"
          class="w-7 h-7 shrink-0 flex items-center justify-center rounded-full hover:bg-white/70 text-gray-500"
          title="Dismiss"
        >
          <app-icon name="x" [size]="14"></app-icon>
        </button>
      </div>
    </div>
  `,
  styles: [`
    /* Shimmer skeleton for the catch-up loading state. Animates a
     * highlight band across a soft purple background to suggest "AI
     * is working" without spinning text. Reduced motion is respected. */
    .catchup-skeleton {
      display: inline-block;
      background: linear-gradient(90deg, rgba(168,85,247,0.10) 0%, rgba(168,85,247,0.22) 50%, rgba(168,85,247,0.10) 100%);
      background-size: 200% 100%;
      animation: catchupShimmer 1.4s ease-in-out infinite;
    }
    @keyframes catchupShimmer {
      0%   { background-position: 200% 0; }
      100% { background-position: -200% 0; }
    }
    @media (prefers-reduced-motion: reduce) {
      .catchup-skeleton { animation: none; }
    }
  `],
})
export class AICatchupBannerComponent implements OnChanges {
  state = inject(ChatStateService);

  @Input({ required: true }) convId!: string;

  /** Per-instance dismissal — cleared on refresh so the banner returns. */
  private dismissed = signal(false);

  /** Backend-loaded summary (live mode). Populated by `hydrate` when
   *  the conv is unread. Stays null in offline/demo mode → banner hides. */
  private serverSummary = signal<{ severity: string; summary: string; actions: string[] } | null>(null);

  /** True while the AI is producing the summary. Used to render a
   *  pulsing skeleton in the banner instead of empty content. */
  loading = signal(false);

  summary = computed(() => this.serverSummary());

  /** Show whenever a summary is available (or being loaded) and the
   *  user hasn't dismissed it. The "must be unread" gate was removed
   *  on purpose — users want a recap on read conversations too, e.g.
   *  re-opening a chat from yesterday. The summary is cached at
   *  chat-state.aiSummaryByConv so flipping between convs doesn't
   *  hammer the LLM. */
  visible = computed(() => {
    if (this.dismissed()) return false;
    return !!this.summary() || this.loading();
  });

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["convId"]) {
      this.dismissed.set(false);
      this.serverSummary.set(null);
      void this.hydrate();
    }
  }

  /** Pull the AI catch-up summary for the active conv. Routes through
   *  chat-state's cache so flipping between convs doesn't refire the
   *  LLM call. The cache is invalidated automatically when a new
   *  message.created FCM payload arrives for this channel. */
  private async hydrate(): Promise<void> {
    if (!this.state.live()) return;
    this.loading.set(true);
    try {
      const res = await this.state.loadAISummaryLive(this.convId);
      if (!res || !res.summary) {
        this.serverSummary.set(null);
        return;
      }
      this.serverSummary.set({
        severity: this.severityFromCount(res.messageCount ?? 0),
        summary: res.summary,
        actions: extractActionsFromMarkdown(res.summary),
      });
    } finally {
      this.loading.set(false);
    }
  }

  /** Heuristic — purely cosmetic; the LLM doesn't return severity. */
  private severityFromCount(n: number): string {
    if (n >= 25) return "high";
    if (n >= 10) return "medium";
    return "low";
  }

  severityClass = computed(() => {
    const sev = this.summary()?.severity;
    const base = "text-[10px] font-semibold uppercase tracking-wider px-1.5 py-0.5 rounded";
    if (sev === "high")   return `${base} bg-red-100 text-red-700`;
    if (sev === "medium") return `${base} bg-amber-100 text-amber-700`;
    return `${base} bg-gray-100 text-gray-600`;
  });

  markRead(): void {
    if (this.state.live()) {
      void this.state.markConvReadLive(this.convId);
    } else {
      this.state.markConvRead(this.convId);
    }
  }

  dismiss(): void {
    this.dismissed.set(true);
  }
}

/** Pull short markdown bullets out of the LLM's summary string and
 *  surface them as action chips beside the headline. The first bullet
 *  is treated as the headline; the rest become chips. */
function extractActionsFromMarkdown(md: string): string[] {
  const lines = md.split(/\n+/).map((l) => l.trim()).filter(Boolean);
  const bullets = lines
    .filter((l) => l.startsWith("- ") || l.startsWith("* "))
    .map((l) => l.replace(/^[-*]\s+/, ""));
  // First bullet stays in `summary` as the main line; remainders become chips.
  return bullets.slice(1, 4);
}
