import { ChangeDetectionStrategy, Component, Input, computed, inject, signal } from "@angular/core";
import { CommonModule } from "@angular/common";
import { ChatStateService } from "../../services/chat-state.service";
import { AI_UNREAD_SUMMARIES } from "../../data/dashboard";
import { IconComponent } from "../icon/icon.component";

/**
 * "Catch me up" banner shown inline at the top of an unread conversation.
 * If the AI has prepared a summary for this conv (via AI_UNREAD_SUMMARIES),
 * the user gets a one-tap recap with the actions the AI thinks they should
 * take next — saves them having to scroll back through dozens of messages.
 *
 * Visibility rules:
 *   - The conv must have an entry in AI_UNREAD_SUMMARIES
 *   - The conv must be unread (no summary banner needed if you've already
 *     caught up)
 *   - The user can dismiss the banner — that state is per-tab (signal),
 *     not persisted; refreshing brings it back so the user can re-check.
 */
@Component({
  selector: "app-ai-catchup-banner",
  standalone: true,
  imports: [CommonModule, IconComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div *ngIf="visible()"
         class="mx-3 mt-3 mb-1 rounded-2xl border border-purple-100 bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50 p-3 shadow-sm">
      <div class="flex items-start gap-3">
        <div class="w-7 h-7 shrink-0 rounded-md bg-gradient-to-br from-blue-500 via-purple-500 to-pink-500 flex items-center justify-center">
          <app-icon name="sparkles" [size]="14" class="text-white"></app-icon>
        </div>
        <div class="flex-1 min-w-0">
          <div class="flex items-baseline gap-2 flex-wrap">
            <span class="text-[11px] font-bold uppercase tracking-wider text-purple-700">Catch me up</span>
            <span [class]="severityClass()">{{ summary()?.severity }}</span>
          </div>
          <div class="text-[13px] text-gray-800 mt-1 leading-relaxed">{{ summary()?.summary }}</div>

          <!-- Suggested actions -->
          <div *ngIf="summary()?.actions?.length" class="flex items-center gap-1.5 mt-2 flex-wrap">
            <span *ngFor="let a of summary()?.actions"
                  class="text-[11px] bg-white/80 ring-1 ring-purple-100 text-purple-700 rounded-full px-2 py-0.5">
              {{ a }}
            </span>
          </div>

          <!-- Footer actions -->
          <div class="flex items-center gap-2 mt-2.5">
            <button
              (click)="markRead()"
              class="text-[12px] font-medium text-purple-700 hover:text-purple-900 px-2 py-1 rounded hover:bg-white/70 transition"
            >Mark as read</button>
            <span class="text-gray-300">·</span>
            <button
              (click)="dismiss()"
              class="text-[12px] text-gray-500 hover:text-gray-800 px-2 py-1 rounded hover:bg-white/70 transition"
            >Dismiss</button>
            <span class="text-[10px] text-gray-400 ml-auto">Generated by Airlift Intelligence</span>
          </div>
        </div>

        <!-- Quick close X -->
        <button
          (click)="dismiss()"
          class="w-7 h-7 shrink-0 flex items-center justify-center rounded-full hover:bg-white/70 text-gray-500"
          title="Dismiss"
        >
          <app-icon name="x" [size]="14"></app-icon>
        </button>
      </div>
    </div>
  `,
})
export class AICatchupBannerComponent {
  state = inject(ChatStateService);

  @Input({ required: true }) convId!: string;

  /** Per-instance dismissal — cleared on refresh so the banner returns. */
  private dismissed = signal(false);

  summary = computed(() => AI_UNREAD_SUMMARIES[this.convId] || null);

  /** Show only when there's a summary, the conv is still unread, and the
   *  user hasn't dismissed the banner yet. */
  visible = computed(() => {
    if (this.dismissed()) return false;
    if (!this.summary()) return false;
    const conv = this.state.conversations().find((c) => c.id === this.convId);
    return !!conv?.unread;
  });

  severityClass = computed(() => {
    const sev = this.summary()?.severity;
    const base = "text-[10px] font-semibold uppercase tracking-wider px-1.5 py-0.5 rounded";
    if (sev === "high")   return `${base} bg-red-100 text-red-700`;
    if (sev === "medium") return `${base} bg-amber-100 text-amber-700`;
    return `${base} bg-gray-100 text-gray-600`;
  });

  markRead(): void {
    this.state.markConvRead(this.convId);
  }

  dismiss(): void {
    this.dismissed.set(true);
  }
}
